# Generated by Django 4.0.6 on 2022-07-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_coursestudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.student'),
        ),
        migrations.DeleteModel(
            name='CourseStudents',
        ),
    ]
