# Generated by Django 4.0.6 on 2022-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_students_delete_coursestudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
